### ISSUE TITLE
Consider dropping `python-` prefix from PyPI package

### ISSUE THREAD

**Issue by Gadgetoid** [ldonjibson/python_monnify#1]
Your package is released onto PyPi as `https://pypi.org/project/python-monnify/`

However:

1. `python-` is redundant, it's a Python library
2. The name `monnify` appears to be available - https://pypi.org/project/monnify/
3. This could present a security flaw since anyone could register `monnify` and be easily confused for your package

**Comment by ldonjibson** [comment]
oh! thanks,
I created a new one as you have suggested.
here is the link:
https://github.com/ldonjibson/monnify
https://pypi.org/project/monnify/
